theme: minimal
description: Site web du réseau des masters CHPS
url: "https://ddavid42.github.io/chps"
markdown: kramdown
highlighter: rouge

header_pages:
 - index.md
 - consortium.md
 - stages.md
 - about.md